def plot(file)
	a=aread(file)
	mid=np.where(a.rho==a.rho.max())
	r=np.sqrt((a.x-a.x[mid])**2+(a.y-a.y[mid])**2+(a.z-a.z[mid])**2)
	heat=np.array([8,9,10,11,12,20,21,22,23,24,25])
	cool=np.array([0,1,2,3,4,6,7,13,14,15,16,17,18,19,26])
	tff=np.sqrt(3*np.pi/(32*ap.G.cgs.value*a.rho*rho_cu))
	plt.scatter(a.rho*rho_cu,abs(a.u/np.sum(a.cooling[:,heat],1)),c='r',label=r'$t_h$',s=0.1)
	plt.scatter(a.rho*rho_cu,abs(a.u/np.sum(a.cooling[:,cool],1)),c='aqua',label=r'$t_c$',s=0.1)
	plt.ylim(abs(a.u/np.sum(a.cooling[:,cool],1)).min(),abs(a.u/np.sum(a.cooling[:,cool],1)).max())
	plt.xlim(a.rho.min()*rho_cu,a.rho.max()*rho_cu)
	plt.yscale('log')
	plt.xscale('log')
	plt.scatter(a.rho*rho_cu,tff,c='dimgrey',label=r'$t_{ff}$',s=0.1)
	plt.scatter(a.rho*rho_cu,abs(a.u/np.sum(a.cooling[:,heat],1))+tff,c='firebrick',label=r'$t_h + t_{ff}$',s=0.1)
	plt.xlabel(r'$\rho$ [gcm$^{-3}$]',fontsize=20)
	plt.ylabel('t [s]       ',fontsize=20,rotation=0)
	plt.legend(fontsize=10,frameon=False,markerscale=15)
	plt.tick_params(axis="x", labelsize=15,direction="in")
	plt.tick_params(axis="y", labelsize=15,direction="in")
	plt.subplots_adjust(left = 0.2,bottom = 0.17,right=0.9)

